#!/usr/bin/env bash

xrandr --output DP-0 --mode 2560x1440 --rate 144.0 --primary
xrandr --output DP-4 --mode 1920x1080 --rate 60.0 --right-of DP-0
xrandr --output HDMI-1 --mode 3840x2160 --rate 60.0 --rotate left --left-of DP-0
